const CONFIG = {
    titleWeb: "Gửi cho chú <3",
    introTitle: 'Chú Bí iu dấu ui',
    introDesc: `và cháu chỉ cần chủ biết một điều duy nhất là cháu thích chú`,
    btnIntro: '^^HiHi^^',
    title: 'Có biết trái tim em đang rung rinh lên chỉ vì anh? 🥰',
    desc: 'Liệu chú có thích cháu không ? ',
    btnYes: 'có nha <33',
    btnNo: 'Không nha :3',
    question: 'Trên thế giới hơn 7 tỉ người mà sao chsu lại thích cháu <3',
    btnReply: 'Gửi cho cháu <3',
    reply: 'Vì cháu dễ thương lắm đó <33333333',
    mess: 'cháu biết mà 🥰. Iu chú Bí moa moa 😘😘',
    messDesc: 'Tối nay cháu hát chú nghe nha <3.',
    btnAccept: 'Okiiiii lun <3',
  
