const CONFIG = {
    titleWeb: "Gửi cho chú <3",
    introTitle: 'Chú Bí iu dấu ưi',
    introDesc: `và cháu chỉ cần chú biê một điều duy nhất là : CHÁU THÍCH CHÚ <3 `,
    btnIntro: '^^HiHi^^',
    title: 'Có biết trái tym cháu đang rung rinh lên chỉ vì chú 🥰',
    desc: 'liệu chú có thích cháu không ? ',
    btnYes: 'Thích lắm <33',
    btnNo: 'Không nha :3',
    question: 'Trên thế giới hơn 7 tỉ người mà sao chú lại thích cháu <3',
    btnReply: 'Gửi cho cháu <3',
    reply: 'Vì cháu dễ thương lắm lun đó <33333333',
    mess: 'Mình biết mà 🥰. Iu chú Bí moa moa 😘😘',
    messDesc: 'Tối nay cháu hát chú nghe nha <3.',
    btnAccept: 'Okiiiii lun <3',
    
